# Generated by Django 4.1.5 on 2023-02-07 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_by_two', models.CharField(max_length=30)),
                ('three_by_three', models.CharField(max_length=30)),
                ('four_by_four', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('results', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userresults')),
            ],
        ),
    ]
