# Generated by Django 4.1.5 on 2023-02-08 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_userprofile_results_userprofile_signup_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserResults',
            new_name='ProfileResults',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='signup',
            new_name='signup_date',
        ),
    ]
